"use client"

import { useState, useEffect } from "react"
import { useBrandContext } from '@/lib/context/BrandContext'
import { DateRange } from "react-day-picker"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { startOfDay, endOfDay, format, startOfMonth, endOfMonth, subMonths, differenceInHours, addHours, isFirstDayOfMonth, addMonths } from "date-fns"
import { Skeleton } from "@/components/ui/skeleton"
import { Loader2, BarChart4, Calendar, RefreshCw, Clock, Zap, MoreHorizontal, Filter, ChevronRight, CircleIcon, ArrowUpRight, Download } from "lucide-react"
import { useToast } from "@/components/ui/use-toast"
import { supabase } from '@/lib/supabase'
import { cn } from "@/lib/utils"
import { useUser } from "@clerk/nextjs"
import { ResponsiveContainer, LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip as ReTooltip } from "recharts"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Input } from "@/components/ui/input"

export default function MarketingAssistantPage() {
  const { toast } = useToast()
  const { user } = useUser()
  const { selectedBrandId, brands } = useBrandContext()
  const [dateRange, setDateRange] = useState<DateRange>({
    from: startOfDay(new Date()),
    to: endOfDay(new Date()),
  })
  const [isLoadingReport, setIsLoadingReport] = useState(false)
  const [aiReport, setAiReport] = useState<string>("")
  const [reportData, setReportData] = useState<any>(null)
  const [selectedPeriod, setSelectedPeriod] = useState<string>("today")
  const [forceRefresh, setForceRefresh] = useState(false)
  const [lastRefreshed, setLastRefreshed] = useState<Date | null>(null)
  const [nextRefreshTime, setNextRefreshTime] = useState<Date | null>(null)

  // Get greeting based on time of day
  const getGreeting = () => {
    const hour = new Date().getHours()
    if (hour < 12) return "Good morning"
    if (hour < 18) return "Good afternoon"
    return "Good evening"
  }

  // Get user's first name
  const getUserFirstName = () => {
    if (!user) return ""
    return user.firstName || user.fullName?.split(' ')[0] || ""
  }

  // Handle period selection
  const handlePeriodSelect = (value: string) => {
    setSelectedPeriod(value)
    
    const now = new Date()
    let from: Date
    let to: Date
    
    switch (value) {
      case "today":
        from = startOfDay(now)
        to = endOfDay(now)
        break
      case "last-month": {
        // Get the first and last day of last month
        const lastMonth = subMonths(now, 1)
        from = startOfMonth(lastMonth)
        to = endOfMonth(lastMonth)
        break
      }
      default:
        from = startOfDay(now)
        to = endOfDay(now)
    }
    
    setDateRange({
      from,
      to
    })
  }

  // Check if a report exists in the database
  const checkExistingReport = async (brandId: string, fromDate: string, toDate: string, periodName: string) => {
    try {
      console.log('Checking for existing report in database...')
      const { data, error } = await supabase
        .from('ai_marketing_reports')
        .select('*')
        .eq('brand_id', brandId)
        .eq('date_range_from', fromDate)
        .eq('date_range_to', toDate)
        .eq('period_name', periodName)
        .order('created_at', { ascending: false })
        .limit(1)
      
      if (error) {
        console.error('Error checking for existing report:', error)
        return null
      }
      
      if (data && data.length > 0) {
        console.log('Found existing report from:', new Date(data[0].created_at))
        return data[0]
      } else {
        console.log('No existing report found in database')
        return null
      }
    } catch (error) {
      console.error('Exception checking for existing report:', error)
      return null
    }
  }

  // Apply current styling to an existing report content
  const applyCurrentStyling = (existingReport: any) => {
    if (!existingReport || !existingReport.raw_response) {
      return null
    }
    
    console.log('Applying current styling to existing report content')
    
    // Get the current report style version
    const REPORT_STYLE_VERSION = 4
    
    // Extract the raw AI content generated by OpenAI
    const rawContent = existingReport.raw_response
    
    // Apply the current styling to the content (similar to what the API does)
    let enhancedMarkdown = rawContent
      .replace(/^## (.*$)/gm, '<h2 class="text-xl font-bold mt-6 mb-3 text-white">$1</h2>')
      .replace(/^### (.*$)/gm, '<h3 class="text-lg font-semibold mt-4 mb-2 text-white">$1</h3>')
      .replace(/\*\*(.*?)\*\*/g, '<span class="font-bold text-white">$1</span>')
    
    // Convert to HTML using simple regex replacements
    const contentHtml = enhancedMarkdown
      .replace(/\n\n/g, '</p><p>')
      .replace(/\n/g, '<br/>')
      
    // Create a professional report with current styling
    const brandName = brands.find(brand => brand.id === selectedBrandId)?.name || "Your Brand"
    const reportDate = format(new Date(existingReport.created_at), 'MMMM d, yyyy')
    const reportPeriod = existingReport.period_name === "today" 
      ? "Today's Performance" 
      : `Performance for ${format(new Date(existingReport.date_range_from), 'MMMM yyyy')}`
    
    const greeting = `${getGreeting()}, ${getUserFirstName()}`
    
    // Use current professional report template with existing content
    return `
      <div class="report-container" data-style-version="${REPORT_STYLE_VERSION}">
        <!-- Official Report Header -->
        <div class="report-header-wrapper">
          <div class="report-logo-container">
            <div class="report-logo-stamp">
              <img src="/brand/favicon-96x96.png" alt="Brez Logo" width="64" height="64" />
            </div>
          </div>
          
          <div class="report-header">
            <div class="report-title-section">
              <h1 class="report-title">MARKETING INSIGHTS REPORT</h1>
              <p class="report-official">OFFICIAL DOCUMENT</p>
            </div>
            
            <div class="report-meta">
              <table class="report-info-table">
                <tr>
                  <td class="report-info-label">Brand:</td>
                  <td class="report-info-value">${brandName}</td>
                </tr>
                <tr>
                  <td class="report-info-label">Period:</td>
                  <td class="report-info-value">${reportPeriod}</td>
                </tr>
                <tr>
                  <td class="report-info-label">Generated:</td>
                  <td class="report-info-value">${reportDate}</td>
                </tr>
                <tr>
                  <td class="report-info-label">Report ID:</td>
                  <td class="report-info-value font-mono">${existingReport.id}</td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        
        <!-- Report Content -->
        <div class="report-content">
          <div class="space-y-4">
            ${contentHtml}
          </div>
        </div>
        
        <!-- Report Footer -->
        <div class="report-footer">
          <div class="footer-brand">
            <img src="/brand/favicon-96x96.png" alt="Brez Logo" width="24" height="24" />
            <span>Powered by Brez Marketing Assistant</span>
          </div>
          <div class="footer-legal">
            <p>CONFIDENTIAL &amp; PROPRIETARY</p>
            <p class="report-timestamp">${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}</p>
          </div>
        </div>
        
        <style>
          .report-container {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            color: #e2e8f0;
            margin: 0;
            padding: 0;
            background-color: #121212;
            position: relative;
            border-radius: 8px;
            overflow: hidden;
            border: 1px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.3);
          }
          
          .report-header-wrapper {
            position: relative;
            background: linear-gradient(135deg, #1a1a1a 0%, #222 100%);
            padding: 2rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
          }
          
          .report-logo-container {
            position: absolute;
            top: 1.5rem;
            right: 2rem;
          }
          
          .report-logo-stamp {
            display: flex;
            align-items: center;
            justify-content: center;
            background: rgba(0, 0, 0, 0.3);
            border-radius: 8px;
            padding: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            border: 1px solid rgba(255, 255, 255, 0.1);
          }
          
          .report-header {
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
            max-width: calc(100% - 100px);
          }
          
          .report-title-section {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
          }
          
          .report-title {
            font-size: 1.75rem;
            font-weight: 700;
            letter-spacing: 0.05em;
            margin: 0;
            color: #fff;
            padding-bottom: 0.5rem;
            border-bottom: 3px solid rgba(255, 255, 255, 0.2);
            width: 100%;
            max-width: 500px;
          }
          
          .report-official {
            font-size: 0.7rem;
            letter-spacing: 0.2em;
            font-weight: 500;
            color: #94a3b8;
            margin: 0.5rem 0 0 0;
            text-transform: uppercase;
          }
          
          .report-info-table {
            border-collapse: separate;
            border-spacing: 0 0.25rem;
          }
          
          .report-info-label {
            color: #94a3b8;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            padding-right: 1rem;
            white-space: nowrap;
          }
          
          .report-info-value {
            color: #e2e8f0;
            font-size: 0.875rem;
          }
          
          .report-greeting-banner {
            background: linear-gradient(90deg, #1a1a1a 0%, #111 100%);
            padding: 1.5rem 2rem;
            border-left: 3px solid rgba(255, 255, 255, 0.3);
            margin: 2rem;
          }
          
          .greeting-text {
            font-size: 1.5rem;
            font-weight: 600;
            margin: 0;
            color: #fff;
          }
          
          .greeting-subtext {
            margin: 0.5rem 0 0 0;
            color: #94a3b8;
            font-size: 0.9rem;
          }
          
          .report-content {
            padding: 0 2rem 2rem 2rem;
            margin-top: 2rem;
            font-size: 15px;
            line-height: 1.6;
          }
          
          .report-content h2 {
            margin-top: 2.5rem !important;
            padding-bottom: 0.75rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            font-size: 1.4rem;
            color: #fff !important;
            font-weight: 600;
          }
          
          .report-content h2:first-child {
            margin-top: 0 !important;
          }
          
          .report-content h3 {
            color: #fff !important;
            font-size: 1.2rem;
            margin-top: 1.5rem;
            margin-bottom: 0.75rem;
            font-weight: 600;
          }
          
          .report-content ul {
            margin-left: 1.5rem;
            margin-bottom: 1.5rem;
            padding-left: 0;
          }
          
          .report-content li {
            margin-bottom: 0.5rem;
            line-height: 1.6;
          }
          
          .report-content p {
            line-height: 1.6;
            margin-bottom: 1rem;
          }
          
          .report-footer {
            background: #0a0a0a;
            padding: 1.5rem 2rem;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          
          .footer-brand {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            color: #94a3b8;
            font-size: 0.8rem;
          }
          
          .footer-legal {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
            gap: 0.25rem;
            font-size: 0.7rem;
            color: #64748b;
          }
          
          .footer-legal p {
            margin: 0;
          }
          
          .report-timestamp {
            font-family: monospace;
          }
          
          .font-mono {
            font-family: monospace;
          }
          
          .report-content span.font-bold {
            color: #fff !important;
            font-weight: 600 !important;
          }
          
          .report-content > div > h2:first-child {
            margin-top: 0 !important;
          }
        </style>
      </div>
    `
  }

  // Calculate when the report can be refreshed next
  const calculateNextRefreshTime = (createdAt: Date) => {
    const now = new Date()
    
    if (selectedPeriod === "today") {
      // For today, next refresh is 3 hours after creation
      return addHours(createdAt, 3)
    } else if (selectedPeriod === "last-month") {
      // For last month, next refresh is the 1st of next month
      const nextMonth = addMonths(now, 1)
      return startOfDay(startOfMonth(nextMonth))
    }
    
    return null
  }

  // Format next refresh time message
  const getNextRefreshMessage = () => {
    if (!nextRefreshTime) return ""
    
    const now = new Date()
    
    if (nextRefreshTime <= now) {
      return "Available for refresh now"
    }
    
    if (selectedPeriod === "today") {
      return `Refreshable after ${format(nextRefreshTime, 'h:mm a')}`
    } else if (selectedPeriod === "last-month") {
      return `Will refresh on ${format(nextRefreshTime, 'MMMM d, yyyy')}`
    }
    
    return `Next refresh: ${format(nextRefreshTime, 'MMM d, yyyy h:mm a')}`
  }

  // Generate report
  const generateAiReport = async (forceRefreshReport = false) => {
    if (!selectedBrandId) {
      toast({
        title: "No brand selected",
        description: "Please select a brand to generate a report",
        variant: "destructive"
      })
      return
    }

    try {
      setIsLoadingReport(true)
      setAiReport("")

      const fromDate = format(dateRange.from!, 'yyyy-MM-dd')
      const toDate = format(dateRange.to!, 'yyyy-MM-dd')

      console.log(`Generating report for brand ${selectedBrandId} from ${fromDate} to ${toDate}, force refresh: ${forceRefreshReport}`)

      // Completely bypass cache when style version changes to ensure new styles are applied
      // This version number should be incremented whenever the report style changes
      const REPORT_STYLE_VERSION = 4
      
      // Check if we have a cached report
      if (!forceRefreshReport) {
        const existingReport = await checkExistingReport(
          selectedBrandId,
          fromDate,
          toDate,
          selectedPeriod
        )
        
        if (existingReport) {
          // Only use the existing report if it doesn't need to be refreshed based on time
          const createdAt = new Date(existingReport.created_at)
          const now = new Date()
          let shouldUseExisting = false
          
          if (selectedPeriod === "today") {
            // For today's data, refresh every 3 hours
            const hoursSinceCreation = differenceInHours(now, createdAt)
            shouldUseExisting = hoursSinceCreation < 3
          } else if (selectedPeriod === "last-month") {
            // For last month, only refresh on the 1st of the new month
            shouldUseExisting = !isFirstDayOfMonth(now)
          }
          
          // Important: Instead of checking version and regenerating from OpenAI,
          // just apply current styling to the existing report content
          if (shouldUseExisting) {
            console.log('Using existing report with updated styling')
            
            // Apply current styling to existing report content
            const styledReport = applyCurrentStyling(existingReport)
            
            if (styledReport) {
              setAiReport(styledReport)
              setLastRefreshed(createdAt)
              setNextRefreshTime(calculateNextRefreshTime(createdAt))
              setIsLoadingReport(false)
              return
            } else {
              console.log('Failed to apply styling, will generate new report')
            }
          } else {
            console.log('Existing report found but needs time-based refresh')
          }
        } else {
          console.log('No existing report found in database')
        }
      } else {
        console.log('Force refresh requested, generating new report')
      }

      const params = new URLSearchParams({
        brandId: selectedBrandId,
        from: fromDate,
        to: toDate,
        t: Date.now().toString() // Cache buster
      })

      // Get brand info
      const selectedBrand = brands.find(brand => brand.id === selectedBrandId)

      // Fetch all the data needed for the report
      const [shopifyResponse, metaResponse] = await Promise.all([
        fetch(`/api/metrics?${params.toString()}`),
        fetch(`/api/metrics/meta?${params.toString()}`)
      ])

      if (!shopifyResponse.ok || !metaResponse.ok) {
        throw new Error("Failed to fetch metrics data")
      }

      const shopifyData = await shopifyResponse.json()
      const metaData = await metaResponse.json()

      // Add greeting to the report metadata
      const greeting = `${getGreeting()}, ${getUserFirstName()}`

      // Prepare data object for AI analysis
      const dataForAi = {
        date_range: {
          from: fromDate,
          to: toDate,
          period_days: Math.round((dateRange.to!.getTime() - dateRange.from!.getTime()) / (1000 * 60 * 60 * 24)),
          period_name: selectedPeriod
        },
        brand: {
          id: selectedBrandId,
          name: selectedBrand?.name || "Unknown Brand",
          industry: "E-commerce" // Default to E-commerce industry
        },
        platforms: {
          shopify: shopifyData,
          meta: metaData
        },
        user: {
          greeting
        }
      }

      // Store data for debug/display purposes
      setReportData(dataForAi)

      // Send data to AI for analysis
      const aiResponse = await fetch('/api/ai/analyze-marketing', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(dataForAi)
      })

      if (!aiResponse.ok) {
        console.error('API response error:', await aiResponse.text())
        throw new Error("Failed to generate AI report")
      }

      const aiResult = await aiResponse.json()
      console.log('Successfully received AI report')
      
      // Create a professional report with proper design elements, branding, and the greeting at the top
      const brandName = selectedBrand?.name || "Your Brand"
      const reportDate = format(new Date(), 'MMMM d, yyyy')
      const reportPeriod = selectedPeriod === "today" 
        ? "Today's Performance" 
        : `Performance for ${format(dateRange.from!, 'MMMM yyyy')}`
      
      const professionalReport = `
        <div class="report-container" data-style-version="${REPORT_STYLE_VERSION}">
          <!-- Official Report Header -->
          <div class="report-header-wrapper">
            <div class="report-logo-container">
              <div class="report-logo-stamp">
                <img src="/brand/favicon-96x96.png" alt="Brez Logo" width="64" height="64" />
              </div>
            </div>
            
            <div class="report-header">
              <div class="report-title-section">
                <h1 class="report-title">MARKETING INSIGHTS REPORT</h1>
                <p class="report-official">OFFICIAL DOCUMENT</p>
              </div>
              
              <div class="report-meta">
                <table class="report-info-table">
                  <tr>
                    <td class="report-info-label">Brand:</td>
                    <td class="report-info-value">${brandName}</td>
                  </tr>
                  <tr>
                    <td class="report-info-label">Period:</td>
                    <td class="report-info-value">${reportPeriod}</td>
                  </tr>
                  <tr>
                    <td class="report-info-label">Generated:</td>
                    <td class="report-info-value">${reportDate}</td>
                  </tr>
                  <tr>
                    <td class="report-info-label">Report ID:</td>
                    <td class="report-info-value font-mono">${Date.now().toString(36).toUpperCase()}</td>
                  </tr>
                </table>
              </div>
            </div>
          </div>
          
          <!-- Report Content -->
          <div class="report-content">
            ${aiResult.report}
          </div>
          
          <!-- Report Footer -->
          <div class="report-footer">
            <div class="footer-brand">
              <img src="/brand/favicon-96x96.png" alt="Brez Logo" width="24" height="24" />
              <span>Powered by Brez Marketing Assistant</span>
            </div>
            <div class="footer-legal">
              <p>CONFIDENTIAL &amp; PROPRIETARY</p>
              <p class="report-timestamp">${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}</p>
            </div>
          </div>
        </div>
        
        <style>
          .report-container {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            color: #e2e8f0;
            margin: 0;
            padding: 0;
            background-color: #121212;
            position: relative;
            border-radius: 8px;
            overflow: hidden;
            border: 1px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.3);
          }
          
          .report-header-wrapper {
            position: relative;
            background: linear-gradient(135deg, #1a1a1a 0%, #222 100%);
            padding: 2rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
          }
          
          .report-logo-container {
            position: absolute;
            top: 1.5rem;
            right: 2rem;
          }
          
          .report-logo-stamp {
            display: flex;
            align-items: center;
            justify-content: center;
            background: rgba(0, 0, 0, 0.3);
            border-radius: 8px;
            padding: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            border: 1px solid rgba(255, 255, 255, 0.1);
          }
          
          .report-header {
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
            max-width: calc(100% - 100px);
          }
          
          .report-title-section {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
          }
          
          .report-title {
            font-size: 1.75rem;
            font-weight: 700;
            letter-spacing: 0.05em;
            margin: 0;
            color: #fff;
            padding-bottom: 0.5rem;
            border-bottom: 3px solid rgba(255, 255, 255, 0.2);
            width: 100%;
            max-width: 500px;
          }
          
          .report-official {
            font-size: 0.7rem;
            letter-spacing: 0.2em;
            font-weight: 500;
            color: #94a3b8;
            margin: 0.5rem 0 0 0;
            text-transform: uppercase;
          }
          
          .report-info-table {
            border-collapse: separate;
            border-spacing: 0 0.25rem;
          }
          
          .report-info-label {
            color: #94a3b8;
            font-size: 0.75rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            padding-right: 1rem;
            white-space: nowrap;
          }
          
          .report-info-value {
            color: #e2e8f0;
            font-size: 0.875rem;
          }
          
          .report-greeting-banner {
            background: linear-gradient(90deg, #1a1a1a 0%, #111 100%);
            padding: 1.5rem 2rem;
            border-left: 3px solid rgba(255, 255, 255, 0.3);
            margin: 2rem;
          }
          
          .greeting-text {
            font-size: 1.5rem;
            font-weight: 600;
            margin: 0;
            color: #fff;
          }
          
          .greeting-subtext {
            margin: 0.5rem 0 0 0;
            color: #94a3b8;
            font-size: 0.9rem;
          }
          
          .report-content {
            padding: 0 2rem 2rem 2rem;
            margin-top: 2rem;
            font-size: 15px;
            line-height: 1.6;
          }
          
          .report-content h2 {
            margin-top: 2.5rem !important;
            padding-bottom: 0.75rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            font-size: 1.4rem;
            color: #fff !important;
            font-weight: 600;
          }
          
          .report-content h2:first-child {
            margin-top: 0 !important;
          }
          
          .report-content h3 {
            color: #fff !important;
            font-size: 1.2rem;
            margin-top: 1.5rem;
            margin-bottom: 0.75rem;
            font-weight: 600;
          }
          
          .report-content ul {
            margin-left: 1.5rem;
            margin-bottom: 1.5rem;
            padding-left: 0;
          }
          
          .report-content li {
            margin-bottom: 0.5rem;
            line-height: 1.6;
          }
          
          .report-content p {
            line-height: 1.6;
            margin-bottom: 1rem;
          }
          
          .report-footer {
            background: #0a0a0a;
            padding: 1.5rem 2rem;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          
          .footer-brand {
            display: flex;
            align-items: center;
            gap: 0.5rem;
            color: #94a3b8;
            font-size: 0.8rem;
          }
          
          .footer-legal {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
            gap: 0.25rem;
            font-size: 0.7rem;
            color: #64748b;
          }
          
          .footer-legal p {
            margin: 0;
          }
          
          .report-timestamp {
            font-family: monospace;
          }
          
          .font-mono {
            font-family: monospace;
          }
          
          .report-content span.font-bold {
            color: #fff !important;
            font-weight: 600 !important;
          }
          
          .report-content > div > h2:first-child {
            margin-top: 0 !important;
          }
        </style>
      `
      
      setAiReport(professionalReport)
      const currentTime = new Date()
      setLastRefreshed(currentTime)
      setNextRefreshTime(calculateNextRefreshTime(currentTime))

    } catch (error) {
      console.error('Error generating AI report:', error)
      toast({
        title: "Error generating report",
        description: "There was a problem generating your marketing report. Please try again later.",
        variant: "destructive"
      })
    } finally {
      setIsLoadingReport(false)
      setForceRefresh(false)
    }
  }

  // Generate report when date range or brand changes
  useEffect(() => {
    if (selectedBrandId && dateRange.from && dateRange.to) {
      generateAiReport(forceRefresh)
    }
  }, [selectedBrandId, dateRange.from, dateRange.to, forceRefresh])

  // Handle manual refresh
  const handleRefresh = () => {
    setForceRefresh(true)
  }

  // Format last refreshed time
  const formatLastRefreshed = () => {
    if (!lastRefreshed) return ""
    
    return `Last updated: ${format(lastRefreshed, 'MMM d, yyyy h:mm a')}`
  }

  // Helper function to get the total status class
  const getTotalStatus = () => {
    // Mock implementation - would use real data in production
    return "bg-yellow-500/20 text-yellow-400";
  };

  // Helper function to get the badge text
  const getTotalBadgeText = () => {
    // Mock implementation - would use real data in production
    return "5 Active, 3 Limited, 4 Paused";
  };

  // Helper function to generate forecasting data
  const getForecastingData = () => {
    // Mock data for the chart
    return [
      { name: 'Day 1', current: 1.7, projected: 1.7 },
      { name: 'Day 5', current: 1.8, projected: 1.9 },
      { name: 'Day 10', current: 1.9, projected: 2.1 },
      { name: 'Day 15', current: 1.85, projected: 2.3 },
      { name: 'Day 20', current: 1.9, projected: 2.5 },
      { name: 'Day 25', current: 1.95, projected: 2.7 },
      { name: 'Day 30', current: 2.0, projected: 2.9 },
    ];
  };

  // Helper function to format Y axis
  const formatYAxis = (value: any) => {
    return `${value}x`;
  };

  // Helper function to format tooltip values
  const formatTooltipValue = (value: any) => {
    return `${value}x ROAS`;
  };

  // Export the report to PDF
  const exportToPdf = async () => {
    if (!aiReport) {
      toast({
        title: "No report available",
        description: "Generate a report first before exporting to PDF.",
        variant: "destructive"
      });
      return;
    }
    
    try {
      toast({
        title: "Preparing PDF export...",
        description: "Please wait while we generate your PDF."
      });
      
      // Dynamically import the libraries only when needed
      const jspdfPromise = import('jspdf');
      const html2canvasPromise = import('html2canvas');
      
      // Create a temporary container for the report
      const container = document.createElement('div');
      container.className = 'pdf-export-container';
      container.style.position = 'absolute';
      container.style.left = '-9999px';
      container.style.top = '-9999px';
      container.style.width = '800px'; // Fixed width for PDF
      container.style.backgroundColor = '#121212'; // Match background color
      document.body.appendChild(container);
      
      // Get the selected brand name
      const brandName = brands.find(brand => brand.id === selectedBrandId)?.name || "Your Brand";
      
      // Get the current report content but remove the greeting banner section
      const parser = new DOMParser();
      const htmlDoc = parser.parseFromString(aiReport, 'text/html');
      
      // Remove the greeting section if it exists
      const greetingBanner = htmlDoc.querySelector('.report-greeting-banner');
      if (greetingBanner) {
        greetingBanner.remove();
      }
      
      // Remove any export-exclude elements (like greetings)
      const excludedElements = htmlDoc.querySelectorAll('.export-exclude');
      excludedElements.forEach(el => el.remove());
      
      // Get the modified report content
      const reportElement = htmlDoc.querySelector('.report-container');
      const reportContent = reportElement ? reportElement.outerHTML : aiReport;
      
      // Insert the content to our container
      container.innerHTML = reportContent;
      
      // Wait for dynamic imports
      const [jspdfModule, html2canvasModule] = await Promise.all([
        jspdfPromise,
        html2canvasPromise
      ]);
      
      // Get the actual height of the report content
      const reportContainer = container.querySelector('.report-container');
      if (!reportContainer) {
        throw new Error("Could not find report container element");
      }
      
      // Ensure the container and all its children are visible for height calculation
      const allElements = container.querySelectorAll('*');
      allElements.forEach(el => {
        if (el instanceof HTMLElement) {
          el.style.visibility = 'visible';
          el.style.display = el.tagName.toLowerCase() === 'div' ? 'block' : '';
        }
      });
      
      // Extract the default exports
      const jsPDF = jspdfModule.default;
      const html2canvas = html2canvasModule.default;
      
      // Render the canvas with proper dimensions
      const canvas = await html2canvas(reportContainer as HTMLElement, {
        scale: 2, // Higher scale for better quality
        useCORS: true,
        logging: false,
        backgroundColor: '#121212', // Match the dark theme background
        windowWidth: 800,
        onclone: (clonedDoc) => {
          // Make sure the footer background extends to the bottom
          const footer = clonedDoc.querySelector('.report-footer');
          if (footer instanceof HTMLElement) {
            footer.style.backgroundColor = '#0a0a0a';
          }
          
          // Final cleanup of any excluded elements
          const excludedElements = clonedDoc.querySelectorAll('.export-exclude');
          excludedElements.forEach(el => el.remove());
        }
      });
      
      // Get canvas dimensions
      const imgWidth = 210; // A4 width in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      // Create new jsPDF instance with dimensions that match content
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: [imgWidth, imgHeight + 1], // Add a small buffer
        hotfixes: ['px_scaling']
      });
      
      // Convert canvas to image
      const imgData = canvas.toDataURL('image/png');
      
      // Add image to PDF
      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      
      // Save PDF
      pdf.save(`${brandName.replace(/\s+/g, '_')}_Marketing_Report_${format(new Date(), 'yyyyMMdd')}.pdf`);
      
      // Remove the temporary container
      document.body.removeChild(container);
      
      toast({
        title: "PDF export successful",
        description: "The marketing report has been downloaded.",
        variant: "default"
      });
    } catch (error) {
      console.error("Error exporting PDF:", error);
      toast({
        title: "Failed to export PDF",
        description: "An error occurred while creating the PDF.",
        variant: "destructive"
      });
    }
  };

  return (
    <div className="max-w-[1600px] mx-auto px-8 py-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-semibold text-white">Marketing Assistant</h1>
          <p className="text-gray-400 mt-1">AI-powered marketing insights and recommendations</p>
        </div>
        
        <div className="flex items-center gap-4">
          <div className="flex gap-2">
            <Select 
              value={selectedPeriod} 
              onValueChange={handlePeriodSelect}
            >
              <SelectTrigger className="w-[120px] bg-[#1A1A1A] border-[#333]">
                <SelectValue placeholder="Select time period" />
              </SelectTrigger>
              <SelectContent className="bg-[#1A1A1A] border-[#333]">
                <SelectItem value="today">Today</SelectItem>
                <SelectItem value="last-month">Last Month</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <Button 
            variant="outline" 
            size="sm" 
            onClick={handleRefresh} 
            disabled={isLoadingReport || !selectedBrandId}
            className="flex items-center gap-2 bg-[#1A1A1A] border-[#333] hover:bg-[#222] transition-colors"
          >
            {isLoadingReport ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <RefreshCw className="h-4 w-4" />
                Refresh Report
              </>
            )}
          </Button>
          
          <Button 
            variant="outline" 
            size="sm" 
            onClick={exportToPdf} 
            disabled={isLoadingReport || !aiReport}
            className="flex items-center gap-2 bg-[#1A1A1A] border-[#333] hover:bg-[#222] transition-colors"
          >
            <Download className="h-4 w-4" />
            Export PDF
          </Button>
        </div>
      </div>
      
      <Tabs defaultValue="report" className="w-full">
        <TabsList className="mb-4 bg-[#1A1A1A]">
          <TabsTrigger value="report" className="data-[state=active]:bg-[#2A2A2A]">
            <BarChart4 className="h-4 w-4 mr-2" />
            Marketing Report
          </TabsTrigger>
          <TabsTrigger value="campaign-optimizer" className="data-[state=active]:bg-[#2A2A2A]">
            <Zap className="h-4 w-4 mr-2" />
            Campaign Optimizer
          </TabsTrigger>
        </TabsList>
        
        <TabsContent value="report" className="space-y-4">
          {!selectedBrandId ? (
            <Card className="bg-[#1A1A1A] border-[#333] text-white">
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center py-12">
                  <BarChart4 className="h-12 w-12 text-gray-500 mb-4" />
                  <h3 className="text-lg font-medium mb-2">No Brand Selected</h3>
                  <p className="text-gray-400 text-center max-w-md">
                    Please select a brand from the sidebar to view its marketing report.
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : isLoadingReport ? (
            <Card className="bg-[#1A1A1A] border-[#333] text-white">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Skeleton className="h-6 w-48 bg-[#2A2A2A]" />
                </CardTitle>
                <CardDescription>
                  <Skeleton className="h-4 w-96 bg-[#2A2A2A]" />
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <Skeleton className="h-4 w-full bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-full bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-3/4 bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-full bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-5/6 bg-[#2A2A2A]" />
              </CardContent>
            </Card>
          ) : aiReport ? (
            <Card className="bg-[#1A1A1A] border-[#333] text-white">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle className="text-xl font-medium text-2xl export-exclude">
                      {getGreeting()}, {getUserFirstName()}
                    </CardTitle>
                  </div>
                  <div className="flex gap-2 items-center">
                    {lastRefreshed && (
                      <div className="text-right export-exclude">
                        <div className="text-xs text-gray-500">
                          {formatLastRefreshed()}
                        </div>
                        {nextRefreshTime && (
                          <div className="text-xs text-gray-500 flex items-center mt-1">
                            <Clock className="h-3 w-3 mr-1 opacity-70" />
                            {getNextRefreshMessage()}
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="prose prose-invert max-w-none" dangerouslySetInnerHTML={{ __html: aiReport }} />
              </CardContent>
            </Card>
          ) : (
            <Card className="bg-[#1A1A1A] border-[#333] text-white">
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center py-12">
                  <RefreshCw className="h-12 w-12 text-gray-500 mb-4" />
                  <h3 className="text-lg font-medium mb-2">No Report Available</h3>
                  <p className="text-gray-400 text-center max-w-md">
                    Click "Generate Report" to create an AI-powered marketing analysis for the selected date range.
                  </p>
                  <Button 
                    className="mt-4 bg-blue-600 hover:bg-blue-700"
                    onClick={() => generateAiReport(true)}
                    disabled={!selectedBrandId}
                  >
                    Generate Report
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>
        
        <TabsContent value="campaign-optimizer" className="space-y-4">
          {!selectedBrandId ? (
            <Card className="bg-[#1A1A1A] border-[#333] text-white">
              <CardContent className="pt-6">
                <div className="flex flex-col items-center justify-center py-12">
                  <Zap className="h-12 w-12 text-gray-500 mb-4" />
                  <h3 className="text-lg font-medium mb-2">No Brand Selected</h3>
                  <p className="text-gray-400 text-center max-w-md">
                    Please select a brand from the sidebar to analyze your campaigns.
                  </p>
                </div>
              </CardContent>
            </Card>
          ) : isLoadingReport ? (
            <Card className="bg-[#1A1A1A] border-[#333] text-white">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Skeleton className="h-6 w-48 bg-[#2A2A2A]" />
                </CardTitle>
                <CardDescription>
                  <Skeleton className="h-4 w-96 bg-[#2A2A2A]" />
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <Skeleton className="h-4 w-full bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-full bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-3/4 bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-full bg-[#2A2A2A]" />
                <Skeleton className="h-4 w-5/6 bg-[#2A2A2A]" />
              </CardContent>
            </Card>
          ) : (
            <>
              {/* Campaign Overview Card */}
              <Card className="bg-[#1A1A1A] border-[#333] text-white">
                <CardHeader className="flex flex-row items-center justify-between pb-2">
                  <div>
                    <CardTitle className="text-xl font-medium">Campaign Overview</CardTitle>
                    <CardDescription>Performance analysis and optimization suggestions</CardDescription>
                  </div>
                  <Button 
                    variant="outline" 
                    size="sm" 
                    onClick={() => generateAiReport(true)}
                    disabled={isLoadingReport}
                    className="flex items-center gap-2 bg-[#1A1A1A] border-[#333] hover:bg-[#222] transition-colors"
                  >
                    {isLoadingReport ? (
                      <>
                        <Loader2 className="h-4 w-4 animate-spin" />
                        Analyzing...
                      </>
                    ) : (
                      <>
                        <RefreshCw className="h-4 w-4" />
                        Refresh Analysis
                      </>
                    )}
                  </Button>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
                    <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                      <div className="flex justify-between items-start">
                        <div>
                          <p className="text-sm text-gray-400 mb-1">Total Campaigns</p>
                          <h3 className="text-2xl font-semibold text-white">12</h3>
                        </div>
                        <Badge className={`px-2 py-1 ${getTotalStatus()} text-xs`}>
                          {getTotalBadgeText()}
                        </Badge>
                      </div>
                      <div className="mt-4 flex items-center gap-3">
                        <div className="grow">
                          <div className="flex justify-between text-xs mb-1">
                            <span className="text-gray-400">Budget Utilization</span>
                            <span className="text-white font-medium">78%</span>
                          </div>
                          <Progress className="h-1.5 bg-[#333] [&>div]:bg-green-500" value={78} />
                        </div>
                      </div>
                    </div>
                    
                    <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                      <div className="flex justify-between items-start">
                        <div>
                          <p className="text-sm text-gray-400 mb-1">Performance Score</p>
                          <h3 className="text-2xl font-semibold text-white">6.8/10</h3>
                        </div>
                        <span className="text-xs rounded-full bg-yellow-500/20 text-yellow-400 px-2 py-1">
                          Needs Improvement
                        </span>
                      </div>
                      <div className="mt-4">
                        <div className="flex justify-between text-xs mb-1">
                          <span className="text-gray-400">ROAS Target: 2.5x</span>
                          <span className="text-white font-medium">Current: 1.9x</span>
                        </div>
                        <Progress className="h-1.5 bg-[#333] [&>div]:bg-green-500" value={76} />
                      </div>
                    </div>
                    
                    <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                      <div className="flex justify-between items-start">
                        <div>
                          <p className="text-sm text-gray-400 mb-1">Optimization Potential</p>
                          <h3 className="text-2xl font-semibold text-white">$1,240/mo</h3>
                        </div>
                        <span className="text-xs rounded-full bg-green-500/20 text-green-400 px-2 py-1">
                          High Impact
                        </span>
                      </div>
                      <div className="mt-4 flex items-center gap-1.5 text-xs text-green-400">
                        <ArrowUpRight className="h-3.5 w-3.5" />
                        <span>16% potential ROAS improvement with suggested changes</span>
                      </div>
                    </div>
                  </div>
                  
                  {/* Action Cards */}
                  <div className="mb-6">
                    <h4 className="text-lg font-semibold mb-3 text-white">Quick Action Center</h4>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
                      <Button variant="outline" className="bg-red-900/20 border-red-900/50 hover:bg-red-900/30 justify-start h-auto py-3">
                        <div className="flex flex-col items-start text-left">
                          <div className="flex items-center w-full justify-between mb-1">
                            <span className="font-medium text-red-400">Pause Underperforming</span>
                            <span className="inline-flex items-center rounded-full border border-red-800 bg-red-500/20 px-2.5 py-0.5 text-xs font-semibold text-red-400">3 Ads</span>
                          </div>
                          <p className="text-xs text-gray-400 font-normal">Spending $48.72/day with no conversions</p>
                        </div>
                      </Button>
                      
                      <Button variant="outline" className="bg-green-900/20 border-green-900/50 hover:bg-green-900/30 justify-start h-auto py-3">
                        <div className="flex flex-col items-start text-left">
                          <div className="flex items-center w-full justify-between mb-1">
                            <span className="font-medium text-green-400">Scale Winners</span>
                            <span className="inline-flex items-center rounded-full border border-green-800 bg-green-500/20 px-2.5 py-0.5 text-xs font-semibold text-green-400">2 Ad Sets</span>
                          </div>
                          <p className="text-xs text-gray-400 font-normal">Increase budget on 3.8x ROAS performers</p>
                        </div>
                      </Button>
                      
                      <Button variant="outline" className="bg-blue-900/20 border-blue-900/50 hover:bg-blue-900/30 justify-start h-auto py-3">
                        <div className="flex flex-col items-start text-left">
                          <div className="flex items-center w-full justify-between mb-1">
                            <span className="font-medium text-blue-400">Consolidate Audiences</span>
                            <span className="inline-flex items-center rounded-full border border-blue-800 bg-blue-500/20 px-2.5 py-0.5 text-xs font-semibold text-blue-400">4 Ad Sets</span>
                          </div>
                          <p className="text-xs text-gray-400 font-normal">Merge overlapping targets to reduce costs</p>
                        </div>
                      </Button>
                      
                      <Button variant="outline" className="bg-purple-900/20 border-purple-900/50 hover:bg-purple-900/30 justify-start h-auto py-3">
                        <div className="flex flex-col items-start text-left">
                          <div className="flex items-center w-full justify-between mb-1">
                            <span className="font-medium text-purple-400">Test New Hook</span>
                            <span className="inline-flex items-center rounded-full border border-purple-800 bg-purple-500/20 px-2.5 py-0.5 text-xs font-semibold text-purple-400">+19% CTR</span>
                          </div>
                          <p className="text-xs text-gray-400 font-normal">Deploy AI-generated hook in top campaign</p>
                        </div>
                      </Button>
                    </div>
                  </div>
                  
                  {/* Daily Checklist */}
                  <div className="mb-6">
                    <h4 className="text-lg font-semibold mb-3 text-white">Today's Optimization Checklist</h4>
                    <div className="space-y-2.5">
                      <div className="flex items-center gap-3 p-3 rounded-md bg-[#222] border border-[#333]">
                        <div className="flex-shrink-0">
                          <CircleIcon className="h-5 w-5 text-green-500 fill-current" />
                        </div>
                        <div className="grow">
                          <p className="text-white text-sm font-medium">Increase budget on "Summer Collection" campaign by 20%</p>
                          <p className="text-xs text-gray-400 mt-0.5">Performing at 2.4x ROAS with consistent results over 7 days</p>
                        </div>
                        <Button size="sm" variant="outline" className="ml-auto bg-[#333] hover:bg-[#444]">Apply</Button>
                      </div>
                      
                      <div className="flex items-center gap-3 p-3 rounded-md bg-[#222] border border-[#333]">
                        <div className="flex-shrink-0">
                          <CircleIcon className="h-5 w-5 text-red-500 fill-current" />
                        </div>
                        <div className="grow">
                          <p className="text-white text-sm font-medium">Pause 3 underperforming ads in "Spring Sale" campaign</p>
                          <p className="text-xs text-gray-400 mt-0.5">No conversions after spending $146.20 (14 days with no results)</p>
                        </div>
                        <Button size="sm" variant="outline" className="ml-auto bg-[#333] hover:bg-[#444]">Apply</Button>
                      </div>
                      
                      <div className="flex items-center gap-3 p-3 rounded-md bg-[#222] border border-[#333]">
                        <div className="flex-shrink-0">
                          <CircleIcon className="h-5 w-5 text-blue-500 fill-current" />
                        </div>
                        <div className="grow">
                          <p className="text-white text-sm font-medium">Split test a new creative in "Core Products" ad set</p>
                          <p className="text-xs text-gray-400 mt-0.5">Current creative has 18% lower CTR than account average</p>
                        </div>
                        <Button size="sm" variant="outline" className="ml-auto bg-[#333] hover:bg-[#444]">Apply</Button>
                      </div>
                      
                      <div className="flex items-center gap-3 p-3 rounded-md bg-[#222] border border-[#333]">
                        <div className="flex-shrink-0">
                          <CircleIcon className="h-5 w-5 text-yellow-500 fill-current" />
                        </div>
                        <div className="grow">
                          <p className="text-white text-sm font-medium">Rebuild audience for "Lookalike 3%" targeting</p>
                          <p className="text-xs text-gray-400 mt-0.5">Showing signs of fatigue with declining CTR (-22% over 14 days)</p>
                        </div>
                        <Button size="sm" variant="outline" className="ml-auto bg-[#333] hover:bg-[#444]">Apply</Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              
              {/* Campaign Performance Card */}
              <Card className="bg-[#1A1A1A] border-[#333] text-white">
                <CardHeader className="pb-2">
                  <CardTitle className="text-xl font-medium">Campaign Deep Dive</CardTitle>
                  <CardDescription>Detailed performance breakdown by campaign, ad set and ad</CardDescription>
                </CardHeader>
                <CardContent>
                  <Tabs defaultValue="table">
                    <div className="flex justify-between items-center mb-4">
                      <TabsList className="bg-[#222]">
                        <TabsTrigger value="table">Table View</TabsTrigger>
                        <TabsTrigger value="cards">Card View</TabsTrigger>
                      </TabsList>
                      
                      <div className="flex items-center gap-2">
                        <Input 
                          placeholder="Search campaigns..." 
                          className="h-8 w-[200px] bg-[#222] border-[#333]"
                        />
                        <Button variant="outline" size="sm" className="bg-[#222] border-[#333] h-8 px-2">
                          <Filter className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                    
                    <TabsContent value="table" className="mt-0">
                      <div className="rounded-md border border-[#333] overflow-hidden">
                        <table className="w-full text-sm">
                          <thead className="bg-[#222] border-b border-[#333]">
                            <tr>
                              <th className="px-4 py-3 text-left font-medium text-gray-400">Campaign</th>
                              <th className="px-4 py-3 text-left font-medium text-gray-400">Status</th>
                              <th className="px-4 py-3 text-right font-medium text-gray-400">Budget</th>
                              <th className="px-4 py-3 text-right font-medium text-gray-400">Spend</th>
                              <th className="px-4 py-3 text-right font-medium text-gray-400">ROAS</th>
                              <th className="px-4 py-3 text-right font-medium text-gray-400">CPA</th>
                              <th className="px-4 py-3 text-right font-medium text-gray-400">Health</th>
                              <th className="px-4 py-3 text-right font-medium text-gray-400">Action</th>
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-[#333]">
                            <tr className="hover:bg-[#222]/50 transition-colors cursor-pointer">
                              <td className="px-4 py-3 text-white">Summer Collection</td>
                              <td className="px-4 py-3">
                                <Badge className="bg-green-500/20 text-green-400 hover:bg-green-500/30">Active</Badge>
                              </td>
                              <td className="px-4 py-3 text-right text-white">$100/day</td>
                              <td className="px-4 py-3 text-right text-white">$2,845.32</td>
                              <td className="px-4 py-3 text-right text-green-400 font-medium">2.4x</td>
                              <td className="px-4 py-3 text-right text-white">$28.45</td>
                              <td className="px-4 py-3 text-right">
                                <div className="flex justify-end">
                                  <div className="w-16 h-2 bg-[#333] rounded-full overflow-hidden">
                                    <div className="h-full bg-green-500" style={{ width: "85%" }}></div>
                                  </div>
                                </div>
                              </td>
                              <td className="px-4 py-3 text-right">
                                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                  <ChevronRight className="h-4 w-4" />
                                </Button>
                              </td>
                            </tr>
                            <tr className="hover:bg-[#222]/50 transition-colors cursor-pointer">
                              <td className="px-4 py-3 text-white">Spring Sale</td>
                              <td className="px-4 py-3">
                                <Badge className="bg-green-500/20 text-green-400 hover:bg-green-500/30">Active</Badge>
                              </td>
                              <td className="px-4 py-3 text-right text-white">$50/day</td>
                              <td className="px-4 py-3 text-right text-white">$1,465.78</td>
                              <td className="px-4 py-3 text-right text-red-400 font-medium">0.8x</td>
                              <td className="px-4 py-3 text-right text-white">$42.12</td>
                              <td className="px-4 py-3 text-right">
                                <div className="flex justify-end">
                                  <div className="w-16 h-2 bg-[#333] rounded-full overflow-hidden">
                                    <div className="h-full bg-red-500" style={{ width: "35%" }}></div>
                                  </div>
                                </div>
                              </td>
                              <td className="px-4 py-3 text-right">
                                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                  <ChevronRight className="h-4 w-4" />
                                </Button>
                              </td>
                            </tr>
                            <tr className="hover:bg-[#222]/50 transition-colors cursor-pointer">
                              <td className="px-4 py-3 text-white">Retargeting Main</td>
                              <td className="px-4 py-3">
                                <Badge className="bg-green-500/20 text-green-400 hover:bg-green-500/30">Active</Badge>
                              </td>
                              <td className="px-4 py-3 text-right text-white">$35/day</td>
                              <td className="px-4 py-3 text-right text-white">$985.42</td>
                              <td className="px-4 py-3 text-right text-green-400 font-medium">3.1x</td>
                              <td className="px-4 py-3 text-right text-white">$21.38</td>
                              <td className="px-4 py-3 text-right">
                                <div className="flex justify-end">
                                  <div className="w-16 h-2 bg-[#333] rounded-full overflow-hidden">
                                    <div className="h-full bg-green-500" style={{ width: "90%" }}></div>
                                  </div>
                                </div>
                              </td>
                              <td className="px-4 py-3 text-right">
                                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                  <ChevronRight className="h-4 w-4" />
                                </Button>
                              </td>
                            </tr>
                            <tr className="hover:bg-[#222]/50 transition-colors cursor-pointer">
                              <td className="px-4 py-3 text-white">Core Products</td>
                              <td className="px-4 py-3">
                                <Badge className="bg-yellow-500/20 text-yellow-400 hover:bg-yellow-500/30">Limited</Badge>
                              </td>
                              <td className="px-4 py-3 text-right text-white">$80/day</td>
                              <td className="px-4 py-3 text-right text-white">$2,240.16</td>
                              <td className="px-4 py-3 text-right text-yellow-400 font-medium">1.5x</td>
                              <td className="px-4 py-3 text-right text-white">$32.78</td>
                              <td className="px-4 py-3 text-right">
                                <div className="flex justify-end">
                                  <div className="w-16 h-2 bg-[#333] rounded-full overflow-hidden">
                                    <div className="h-full bg-yellow-500" style={{ width: "55%" }}></div>
                                  </div>
                                </div>
                              </td>
                              <td className="px-4 py-3 text-right">
                                <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                                  <ChevronRight className="h-4 w-4" />
                                </Button>
                              </td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </TabsContent>
                    
                    <TabsContent value="cards" className="mt-0">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                          <div className="flex justify-between items-start mb-3">
                            <div>
                              <h4 className="font-medium text-white">Summer Collection</h4>
                              <Badge className="mt-1 bg-green-500/20 text-green-400 hover:bg-green-500/30">Active</Badge>
                            </div>
                            <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                              <MoreHorizontal className="h-4 w-4" />
                            </Button>
                          </div>
                          
                          <div className="grid grid-cols-2 gap-4 mb-3">
                            <div>
                              <p className="text-xs text-gray-400">Budget</p>
                              <p className="text-sm font-medium text-white">$100/day</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-400">Spend</p>
                              <p className="text-sm font-medium text-white">$2,845.32</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-400">ROAS</p>
                              <p className="text-sm font-medium text-green-400">2.4x</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-400">CPA</p>
                              <p className="text-sm font-medium text-white">$28.45</p>
                            </div>
                          </div>
                          
                          <div className="mb-3">
                            <div className="flex justify-between text-xs mb-1">
                              <span className="text-gray-400">Performance Health</span>
                              <span className="text-green-400">85%</span>
                            </div>
                            <Progress className="h-1.5 bg-[#333] [&>div]:bg-green-500" value={85} />
                          </div>
                          
                          <Button size="sm" variant="outline" className="w-full bg-[#1A1A1A]">View Details</Button>
                        </div>
                        
                        <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                          <div className="flex justify-between items-start mb-3">
                            <div>
                              <h4 className="font-medium text-white">Spring Sale</h4>
                              <Badge className="mt-1 bg-green-500/20 text-green-400 hover:bg-green-500/30">Active</Badge>
                            </div>
                            <Button variant="ghost" size="sm" className="h-8 w-8 p-0">
                              <MoreHorizontal className="h-4 w-4" />
                            </Button>
                          </div>
                          
                          <div className="grid grid-cols-2 gap-4 mb-3">
                            <div>
                              <p className="text-xs text-gray-400">Budget</p>
                              <p className="text-sm font-medium text-white">$50/day</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-400">Spend</p>
                              <p className="text-sm font-medium text-white">$1,465.78</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-400">ROAS</p>
                              <p className="text-sm font-medium text-red-400">0.8x</p>
                            </div>
                            <div>
                              <p className="text-xs text-gray-400">CPA</p>
                              <p className="text-sm font-medium text-white">$42.12</p>
                            </div>
                          </div>
                          
                          <div className="mb-3">
                            <div className="flex justify-between text-xs mb-1">
                              <span className="text-gray-400">Performance Health</span>
                              <span className="text-red-400">35%</span>
                            </div>
                            <Progress className="h-1.5 bg-[#333] [&>div]:bg-red-500" value={35} />
                          </div>
                          
                          <Button size="sm" variant="outline" className="w-full bg-[#1A1A1A]">View Details</Button>
                        </div>
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
              
              {/* Forecasting Card */}
              <Card className="bg-[#1A1A1A] border-[#333] text-white">
                <CardHeader className="pb-2">
                  <CardTitle className="text-xl font-medium">Performance Forecasting</CardTitle>
                  <CardDescription>Predict campaign performance based on AI modeling</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6">
                    <div className="col-span-2 p-5 rounded-lg bg-[#222] border border-[#333] overflow-hidden">
                      <h4 className="text-lg font-medium mb-4 text-white">Projected ROAS with Optimizations</h4>
                      <div className="h-64">
                        <ResponsiveContainer width="100%" height="100%">
                          <LineChart data={getForecastingData()} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                            <defs>
                              <linearGradient id="colorProjected" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#4ade80" stopOpacity={0.2} />
                                <stop offset="95%" stopColor="#4ade80" stopOpacity={0} />
                              </linearGradient>
                              <linearGradient id="colorCurrent" x1="0" y1="0" x2="0" y2="1">
                                <stop offset="5%" stopColor="#60a5fa" stopOpacity={0.2} />
                                <stop offset="95%" stopColor="#60a5fa" stopOpacity={0} />
                              </linearGradient>
                            </defs>
                            <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                            <XAxis dataKey="name" stroke="#888" fontSize={12} tickLine={false} axisLine={false} />
                            <YAxis stroke="#888" fontSize={12} tickLine={false} axisLine={false} tickFormatter={formatYAxis} />
                            <ReTooltip 
                              contentStyle={{ background: '#222', border: '1px solid #444', borderRadius: '4px' }} 
                              itemStyle={{ color: '#fff' }}
                              formatter={formatTooltipValue} 
                            />
                            <Line type="monotone" dataKey="current" name="Current Trajectory" stroke="#60a5fa" strokeWidth={2} dot={false} activeDot={{ r: 6 }} />
                            <Line type="monotone" dataKey="projected" name="With Optimizations" stroke="#4ade80" strokeWidth={2} dot={false} activeDot={{ r: 6 }} />
                          </LineChart>
                        </ResponsiveContainer>
                      </div>
                    </div>
                    
                    <div className="space-y-4">
                      <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                        <h5 className="text-sm font-medium mb-3 text-white">AI-Recommended Budget Reallocation</h5>
                        <div className="space-y-3">
                          <div>
                            <div className="flex justify-between text-xs mb-1">
                              <span className="text-gray-400">Summer Collection</span>
                              <span className="text-green-400">+30%</span>
                            </div>
                            <Progress className="h-1.5 bg-[#333] [&>div]:bg-green-500" value={80} />
                          </div>
                          <div>
                            <div className="flex justify-between text-xs mb-1">
                              <span className="text-gray-400">Retargeting Main</span>
                              <span className="text-green-400">+15%</span>
                            </div>
                            <Progress className="h-1.5 bg-[#333] [&>div]:bg-green-500" value={65} />
                          </div>
                          <div>
                            <div className="flex justify-between text-xs mb-1">
                              <span className="text-gray-400">Spring Sale</span>
                              <span className="text-red-400">-40%</span>
                            </div>
                            <Progress className="h-1.5 bg-[#333] [&>div]:bg-red-500" value={30} />
                          </div>
                        </div>
                      </div>
                      
                      <div className="p-4 rounded-lg bg-[#222] border border-[#333]">
                        <h5 className="text-sm font-medium mb-1 text-white">Projected Impact Summary</h5>
                        <p className="text-xs text-gray-400 mb-3">Based on 30-day forward modeling</p>
                        <div className="space-y-2">
                          <div className="flex justify-between items-center">
                            <span className="text-sm text-gray-400">ROAS Improvement</span>
                            <span className="text-sm font-medium text-white">+0.7x</span>
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-sm text-gray-400">CPA Reduction</span>
                            <span className="text-sm font-medium text-white">-$8.45</span>
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-sm text-gray-400">Revenue Increase</span>
                            <span className="text-sm font-medium text-white">+$3,240</span>
                          </div>
                          <div className="flex justify-between items-center">
                            <span className="text-sm text-gray-400">Budget Efficiency</span>
                            <span className="text-sm font-medium text-white">+16%</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  
                  <Button className="w-full bg-blue-600 hover:bg-blue-700">
                    Apply AI-Recommended Optimizations
                  </Button>
                </CardContent>
              </Card>
            </>
          )}
        </TabsContent>
      </Tabs>
    </div>
  )
} 