ALTER TABLE public.meta_campaigns
ADD COLUMN IF NOT EXISTS bid_strategy TEXT,
ADD COLUMN IF NOT EXISTS buying_type TEXT,
ADD COLUMN IF NOT EXISTS spend_cap TEXT,
ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS stop_time TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS issues_info JSONB,
ADD COLUMN IF NOT EXISTS pacing_type JSONB,
ADD COLUMN IF NOT EXISTS adlabels JSONB; 