ALTER TABLE public.meta_ads
ADD COLUMN IF NOT EXISTS adlabels JSONB,
ADD COLUMN IF NOT EXISTS tracking_specs JSONB,
ADD COLUMN IF NOT EXISTS recommendations JSONB,
ADD COLUMN IF NOT EXISTS video_id TEXT,
ADD COLUMN IF NOT EXISTS image_crops JSONB,
ADD COLUMN IF NOT EXISTS creative_status TEXT,
ADD COLUMN IF NOT EXISTS url_tags TEXT,
ADD COLUMN IF NOT EXISTS video_data JSONB,
ADD COLUMN IF NOT EXISTS template_data JSONB; 