-- Create sync_logs table for tracking automated sync results
CREATE TABLE IF NOT EXISTS sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_type VARCHAR(50) NOT NULL,
    brands_processed INTEGER DEFAULT 0,
    results JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create index for efficient querying
CREATE INDEX IF NOT EXISTS idx_sync_logs_created_at ON sync_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sync_logs_sync_type ON sync_logs(sync_type);

-- Add RLS (Row Level Security) policy - allow all users to read their sync logs
ALTER TABLE sync_logs ENABLE ROW LEVEL SECURITY;

-- Policy to allow all authenticated users to read sync logs (since these are system-wide)
CREATE POLICY "Allow all authenticated users to read sync logs" 
ON sync_logs 
FOR SELECT 
TO authenticated 
USING (true);

-- Policy to allow service role to insert sync logs (for the cron job)
CREATE POLICY "Allow service role to insert sync logs" 
ON sync_logs 
FOR INSERT 
TO service_role 
WITH CHECK (true);

-- Add comments for documentation
COMMENT ON TABLE sync_logs IS 'Logs for automated data synchronization processes';
COMMENT ON COLUMN sync_logs.sync_type IS 'Type of sync performed (e.g., daily_automated, manual_sync)';
COMMENT ON COLUMN sync_logs.brands_processed IS 'Number of brands that were processed during this sync';
COMMENT ON COLUMN sync_logs.results IS 'JSON object containing detailed results of the sync operation'; 